// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Smc.Infra.Data;

namespace Scm.Infra.Data.Migrations
{
    [DbContext(typeof(ScmDbContext))]
    partial class ScmDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Scm.Domain.Address", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("AddresLineOne")
                        .IsRequired()
                        .HasColumnType("nvarchar(120)")
                        .HasMaxLength(120);

                    b.Property<string>("AddresLineTwo")
                        .HasColumnType("nvarchar(120)")
                        .HasMaxLength(120);

                    b.Property<string>("City")
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.Property<string>("CountyOrProvince")
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.Property<int?>("Number")
                        .HasColumnType("int");

                    b.Property<int>("StudentId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("StudentId");

                    b.ToTable("Addresses");
                });

            modelBuilder.Entity("Scm.Domain.Country", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(500)")
                        .HasMaxLength(500);

                    b.HasKey("Id");

                    b.ToTable("Countries");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Afghanistan"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Albania"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Algeria"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Andorra"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Angola"
                        },
                        new
                        {
                            Id = 6,
                            Name = "antigua and Barbuda"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Argentina"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Armenia"
                        },
                        new
                        {
                            Id = 9,
                            Name = "Australia"
                        },
                        new
                        {
                            Id = 10,
                            Name = "Austria"
                        },
                        new
                        {
                            Id = 11,
                            Name = "Azerbaijan"
                        },
                        new
                        {
                            Id = 12,
                            Name = "Bahamas"
                        },
                        new
                        {
                            Id = 13,
                            Name = "Bahrain"
                        },
                        new
                        {
                            Id = 14,
                            Name = "Bangladesh"
                        },
                        new
                        {
                            Id = 15,
                            Name = "Barbados"
                        },
                        new
                        {
                            Id = 16,
                            Name = "Belarus"
                        },
                        new
                        {
                            Id = 17,
                            Name = "Belgium"
                        },
                        new
                        {
                            Id = 18,
                            Name = "Belize"
                        },
                        new
                        {
                            Id = 19,
                            Name = "Benin"
                        },
                        new
                        {
                            Id = 20,
                            Name = "Bhutan"
                        },
                        new
                        {
                            Id = 21,
                            Name = "Bolivia"
                        },
                        new
                        {
                            Id = 22,
                            Name = "Bosnia Herzegovina"
                        },
                        new
                        {
                            Id = 23,
                            Name = "Botswana"
                        },
                        new
                        {
                            Id = 24,
                            Name = "Brazil"
                        },
                        new
                        {
                            Id = 25,
                            Name = "Brunei"
                        },
                        new
                        {
                            Id = 26,
                            Name = "Bulgaria"
                        },
                        new
                        {
                            Id = 27,
                            Name = "Burkina"
                        },
                        new
                        {
                            Id = 28,
                            Name = "Burundi"
                        },
                        new
                        {
                            Id = 29,
                            Name = "Cambodia"
                        },
                        new
                        {
                            Id = 30,
                            Name = "Cameroon"
                        },
                        new
                        {
                            Id = 31,
                            Name = "Canada"
                        },
                        new
                        {
                            Id = 32,
                            Name = "Cape Verde"
                        },
                        new
                        {
                            Id = 33,
                            Name = "Central African Republic"
                        },
                        new
                        {
                            Id = 34,
                            Name = "Chad"
                        },
                        new
                        {
                            Id = 35,
                            Name = "Chile"
                        },
                        new
                        {
                            Id = 36,
                            Name = "China"
                        },
                        new
                        {
                            Id = 37,
                            Name = "Colombia"
                        },
                        new
                        {
                            Id = 38,
                            Name = "Comoros"
                        },
                        new
                        {
                            Id = 39,
                            Name = "Congo"
                        },
                        new
                        {
                            Id = 40,
                            Name = "Democratic Republic Of Congo"
                        },
                        new
                        {
                            Id = 41,
                            Name = "Costa Rica"
                        },
                        new
                        {
                            Id = 42,
                            Name = "Croatia"
                        },
                        new
                        {
                            Id = 43,
                            Name = "Cuba"
                        },
                        new
                        {
                            Id = 44,
                            Name = "Cyprus"
                        },
                        new
                        {
                            Id = 45,
                            Name = "Czech Republic"
                        },
                        new
                        {
                            Id = 46,
                            Name = "Denmark"
                        },
                        new
                        {
                            Id = 47,
                            Name = "Djibouti"
                        },
                        new
                        {
                            Id = 48,
                            Name = "Dominica"
                        },
                        new
                        {
                            Id = 49,
                            Name = "Dominican Republic"
                        },
                        new
                        {
                            Id = 50,
                            Name = "East Timor"
                        },
                        new
                        {
                            Id = 51,
                            Name = "Ecuador"
                        },
                        new
                        {
                            Id = 52,
                            Name = "Egypt"
                        },
                        new
                        {
                            Id = 53,
                            Name = "El Salvador"
                        },
                        new
                        {
                            Id = 54,
                            Name = "Equatorial Guinea"
                        },
                        new
                        {
                            Id = 55,
                            Name = "Eritrea"
                        },
                        new
                        {
                            Id = 56,
                            Name = "Estonia"
                        },
                        new
                        {
                            Id = 57,
                            Name = "Ethiopia"
                        },
                        new
                        {
                            Id = 58,
                            Name = "Fiji"
                        },
                        new
                        {
                            Id = 59,
                            Name = "Finland"
                        },
                        new
                        {
                            Id = 60,
                            Name = "France"
                        },
                        new
                        {
                            Id = 61,
                            Name = "Gabon"
                        },
                        new
                        {
                            Id = 62,
                            Name = "Gambia"
                        },
                        new
                        {
                            Id = 63,
                            Name = "Georgia"
                        },
                        new
                        {
                            Id = 64,
                            Name = "Germany"
                        },
                        new
                        {
                            Id = 65,
                            Name = "Ghana"
                        },
                        new
                        {
                            Id = 66,
                            Name = "Greece"
                        },
                        new
                        {
                            Id = 67,
                            Name = "Grenada"
                        },
                        new
                        {
                            Id = 68,
                            Name = "Guatemala"
                        },
                        new
                        {
                            Id = 69,
                            Name = "Guinea"
                        },
                        new
                        {
                            Id = 70,
                            Name = "Guinea-Bissau"
                        },
                        new
                        {
                            Id = 71,
                            Name = "Guyana"
                        },
                        new
                        {
                            Id = 72,
                            Name = "Haiti"
                        },
                        new
                        {
                            Id = 73,
                            Name = "Honduras"
                        },
                        new
                        {
                            Id = 74,
                            Name = "Hungary"
                        },
                        new
                        {
                            Id = 75,
                            Name = "Iceland"
                        },
                        new
                        {
                            Id = 76,
                            Name = "India"
                        },
                        new
                        {
                            Id = 77,
                            Name = "Indonesia"
                        },
                        new
                        {
                            Id = 78,
                            Name = "Iran"
                        },
                        new
                        {
                            Id = 79,
                            Name = "Iraq"
                        },
                        new
                        {
                            Id = 80,
                            Name = "Republic Of Ireland"
                        },
                        new
                        {
                            Id = 81,
                            Name = "Israel"
                        },
                        new
                        {
                            Id = 82,
                            Name = "Italy"
                        },
                        new
                        {
                            Id = 83,
                            Name = "Ivory Coast"
                        },
                        new
                        {
                            Id = 84,
                            Name = "Jamaica"
                        },
                        new
                        {
                            Id = 85,
                            Name = "Japan"
                        },
                        new
                        {
                            Id = 86,
                            Name = "Jordan"
                        },
                        new
                        {
                            Id = 87,
                            Name = "Kazakhstan"
                        },
                        new
                        {
                            Id = 88,
                            Name = "Kenya"
                        },
                        new
                        {
                            Id = 89,
                            Name = "Kiribati"
                        },
                        new
                        {
                            Id = 90,
                            Name = "Korea North"
                        },
                        new
                        {
                            Id = 91,
                            Name = "Korea South"
                        },
                        new
                        {
                            Id = 92,
                            Name = "Kosovo"
                        },
                        new
                        {
                            Id = 93,
                            Name = "Kuwait"
                        },
                        new
                        {
                            Id = 94,
                            Name = "Kyrgyzstan"
                        },
                        new
                        {
                            Id = 95,
                            Name = "Laos"
                        },
                        new
                        {
                            Id = 96,
                            Name = "Latvia"
                        },
                        new
                        {
                            Id = 97,
                            Name = "Lebanon"
                        },
                        new
                        {
                            Id = 98,
                            Name = "Lesotho"
                        },
                        new
                        {
                            Id = 99,
                            Name = "Liberia"
                        },
                        new
                        {
                            Id = 100,
                            Name = "Libya"
                        },
                        new
                        {
                            Id = 101,
                            Name = "Liechtenstein"
                        },
                        new
                        {
                            Id = 102,
                            Name = "Lithuania"
                        },
                        new
                        {
                            Id = 103,
                            Name = "Luxembourg"
                        },
                        new
                        {
                            Id = 104,
                            Name = "Macedonia"
                        },
                        new
                        {
                            Id = 105,
                            Name = "Madagascar"
                        },
                        new
                        {
                            Id = 106,
                            Name = "Malawi"
                        },
                        new
                        {
                            Id = 107,
                            Name = "Malaysia"
                        },
                        new
                        {
                            Id = 108,
                            Name = "Maldives"
                        },
                        new
                        {
                            Id = 109,
                            Name = "Mali"
                        },
                        new
                        {
                            Id = 110,
                            Name = "Malta"
                        },
                        new
                        {
                            Id = 111,
                            Name = "Marshall Islands"
                        },
                        new
                        {
                            Id = 112,
                            Name = "Mauritania"
                        },
                        new
                        {
                            Id = 113,
                            Name = "Mauritius"
                        },
                        new
                        {
                            Id = 114,
                            Name = "Mexico"
                        },
                        new
                        {
                            Id = 115,
                            Name = "Micronesia"
                        },
                        new
                        {
                            Id = 116,
                            Name = "Moldova"
                        },
                        new
                        {
                            Id = 117,
                            Name = "Monaco"
                        },
                        new
                        {
                            Id = 118,
                            Name = "Mongolia"
                        },
                        new
                        {
                            Id = 119,
                            Name = "Montenegro"
                        },
                        new
                        {
                            Id = 120,
                            Name = "Morocco"
                        },
                        new
                        {
                            Id = 121,
                            Name = "Mozambique"
                        },
                        new
                        {
                            Id = 122,
                            Name = "Myanmar"
                        },
                        new
                        {
                            Id = 123,
                            Name = "Namibia"
                        },
                        new
                        {
                            Id = 124,
                            Name = "Nauru"
                        },
                        new
                        {
                            Id = 125,
                            Name = "Nepal"
                        },
                        new
                        {
                            Id = 126,
                            Name = "Netherlands"
                        },
                        new
                        {
                            Id = 127,
                            Name = "New Zealand"
                        },
                        new
                        {
                            Id = 128,
                            Name = "Nicaragua"
                        },
                        new
                        {
                            Id = 129,
                            Name = "Niger"
                        },
                        new
                        {
                            Id = 130,
                            Name = "Nigeria"
                        },
                        new
                        {
                            Id = 131,
                            Name = "Norway"
                        },
                        new
                        {
                            Id = 132,
                            Name = "Oman"
                        },
                        new
                        {
                            Id = 133,
                            Name = "Pakistan"
                        },
                        new
                        {
                            Id = 134,
                            Name = "Palau"
                        },
                        new
                        {
                            Id = 135,
                            Name = "Panama"
                        },
                        new
                        {
                            Id = 136,
                            Name = "Papua New Guinea"
                        },
                        new
                        {
                            Id = 137,
                            Name = "Paraguay"
                        },
                        new
                        {
                            Id = 138,
                            Name = "Peru"
                        },
                        new
                        {
                            Id = 139,
                            Name = "Philippines"
                        },
                        new
                        {
                            Id = 140,
                            Name = "Poland"
                        },
                        new
                        {
                            Id = 141,
                            Name = "Portugal"
                        },
                        new
                        {
                            Id = 142,
                            Name = "Qatar"
                        },
                        new
                        {
                            Id = 143,
                            Name = "Romania"
                        },
                        new
                        {
                            Id = 144,
                            Name = "Russian Federation"
                        },
                        new
                        {
                            Id = 145,
                            Name = "Rwanda"
                        },
                        new
                        {
                            Id = 146,
                            Name = "St Kitts and Nevis"
                        },
                        new
                        {
                            Id = 147,
                            Name = "St Lucia"
                        },
                        new
                        {
                            Id = 148,
                            Name = "Saint Vincent &the Grenadines"
                        },
                        new
                        {
                            Id = 149,
                            Name = "Samoa"
                        },
                        new
                        {
                            Id = 150,
                            Name = "San Marino"
                        },
                        new
                        {
                            Id = 151,
                            Name = "Sao Tome &Principe"
                        },
                        new
                        {
                            Id = 152,
                            Name = "Saudi Arabia"
                        },
                        new
                        {
                            Id = 153,
                            Name = "Senegal"
                        },
                        new
                        {
                            Id = 154,
                            Name = "Serbia"
                        },
                        new
                        {
                            Id = 155,
                            Name = "Seychelles"
                        },
                        new
                        {
                            Id = 156,
                            Name = "Sierra Leone"
                        },
                        new
                        {
                            Id = 157,
                            Name = "Singapore"
                        },
                        new
                        {
                            Id = 158,
                            Name = "Slovakia"
                        },
                        new
                        {
                            Id = 159,
                            Name = "Slovenia"
                        },
                        new
                        {
                            Id = 160,
                            Name = "Solomon Islands"
                        },
                        new
                        {
                            Id = 161,
                            Name = "Somalia"
                        },
                        new
                        {
                            Id = 162,
                            Name = "South Africa"
                        },
                        new
                        {
                            Id = 163,
                            Name = "South Sudan"
                        },
                        new
                        {
                            Id = 164,
                            Name = "Spain"
                        },
                        new
                        {
                            Id = 165,
                            Name = "Sri Lanka"
                        },
                        new
                        {
                            Id = 166,
                            Name = "Sudan"
                        },
                        new
                        {
                            Id = 167,
                            Name = "Suriname"
                        },
                        new
                        {
                            Id = 168,
                            Name = "Swaziland"
                        },
                        new
                        {
                            Id = 169,
                            Name = "Sweden"
                        },
                        new
                        {
                            Id = 170,
                            Name = "Switzerland"
                        },
                        new
                        {
                            Id = 171,
                            Name = "Syria"
                        },
                        new
                        {
                            Id = 172,
                            Name = "Taiwan"
                        },
                        new
                        {
                            Id = 173,
                            Name = "Tajikistan"
                        },
                        new
                        {
                            Id = 174,
                            Name = "Tanzania"
                        },
                        new
                        {
                            Id = 175,
                            Name = "Thailand"
                        },
                        new
                        {
                            Id = 176,
                            Name = "Togo"
                        },
                        new
                        {
                            Id = 177,
                            Name = "Tonga"
                        },
                        new
                        {
                            Id = 178,
                            Name = "Trinidad & Tobago"
                        },
                        new
                        {
                            Id = 179,
                            Name = "Tunisia"
                        },
                        new
                        {
                            Id = 180,
                            Name = "Turkey"
                        },
                        new
                        {
                            Id = 181,
                            Name = "Turkmenistan"
                        },
                        new
                        {
                            Id = 182,
                            Name = "Tuvalu"
                        },
                        new
                        {
                            Id = 183,
                            Name = "Uganda"
                        },
                        new
                        {
                            Id = 184,
                            Name = "Ukraine"
                        },
                        new
                        {
                            Id = 185,
                            Name = "United Arab Emirates"
                        },
                        new
                        {
                            Id = 186,
                            Name = "United Kingdom"
                        },
                        new
                        {
                            Id = 187,
                            Name = "United States"
                        },
                        new
                        {
                            Id = 188,
                            Name = "Uruguay"
                        },
                        new
                        {
                            Id = 189,
                            Name = "Uzbekistan"
                        },
                        new
                        {
                            Id = 190,
                            Name = "Vanuatu"
                        },
                        new
                        {
                            Id = 191,
                            Name = "Vatican City"
                        },
                        new
                        {
                            Id = 192,
                            Name = "Venezuela"
                        },
                        new
                        {
                            Id = 193,
                            Name = "Vietnam"
                        },
                        new
                        {
                            Id = 194,
                            Name = "Yemen"
                        },
                        new
                        {
                            Id = 195,
                            Name = "Zambia"
                        },
                        new
                        {
                            Id = 196,
                            Name = "Zimbabwe"
                        });
                });

            modelBuilder.Entity("Scm.Domain.Course", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Capacity")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ChangeDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Code")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeleteDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("TeacherName")
                        .IsRequired()
                        .HasColumnType("nvarchar(150)")
                        .HasMaxLength(150);

                    b.HasKey("Id");

                    b.ToTable("Courses");
                });

            modelBuilder.Entity("Scm.Domain.Student", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime?>("ChangeDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeleteDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(30)")
                        .HasMaxLength(30);

                    b.Property<int>("Gender")
                        .HasColumnType("int");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasColumnType("nvarchar(120)")
                        .HasMaxLength(120);

                    b.HasKey("Id");

                    b.ToTable("Students");
                });

            modelBuilder.Entity("Scm.Domain.StudentCourse", b =>
                {
                    b.Property<int>("StudentId")
                        .HasColumnType("int");

                    b.Property<int>("CourseId")
                        .HasColumnType("int");

                    b.HasKey("StudentId", "CourseId");

                    b.HasIndex("CourseId");

                    b.ToTable("StudentCourses");
                });

            modelBuilder.Entity("Scm.Domain.Address", b =>
                {
                    b.HasOne("Scm.Domain.Country", "Country")
                        .WithMany("Addresses")
                        .HasForeignKey("Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Scm.Domain.Student", "Student")
                        .WithMany("Addresses")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Scm.Domain.StudentCourse", b =>
                {
                    b.HasOne("Scm.Domain.Course", "Course")
                        .WithMany("StudentCourses")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Scm.Domain.Student", "Student")
                        .WithMany("StudentCourses")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
